version: "3.7"
networks:
  default:
    external:
      name: server
services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy/caddy:latest
    env_file:
      - .env
    volumes:
      - ./config:/etc/caddy
      - ./data:/data
      - ./www:/www
      - ./cache:/config
    network_mode: "host"
    ports:
      - 80:80
      - 443:443
    environment:
      ZONE: "${ZONE}"
      EMAIL: "${EMAIL}"
      LAN_RANGE: "${LAN_RANGE}"
      WAN_IP: "${WAN_IP}"
      EXTRA: "${EXTRA}"
      LE_EMAIL: "${LE_EMAIL}"
      HOSTNAME: "${HOSTNAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
